<?php
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/auth.php';
requireLogin();
function countRows($table) { global $pdo; if (!$pdo) return 0; try { return (int)$pdo->query("SELECT COUNT(*) FROM {$table}")->fetchColumn(); } catch (PDOException $e) { return 0; } }
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Dashboard | MACDEF Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet"><link rel="stylesheet" href="../assets/css/style.css"><style>body{background:#f8f9fa}.sidebar{min-height:100vh;background:#002D62;color:#fff}.sidebar .nav-link{color:rgba(255,255,255,.8)}.sidebar .nav-link:hover,.sidebar .nav-link.active{color:#fff;background:rgba(255,255,255,.12)}</style></head>
<body><div class="container-fluid"><div class="row">
<div class="col-md-3 col-lg-2 p-0 sidebar position-fixed d-none d-md-block"><div class="p-4 text-center"><img src="../assets/images/macdef-logo.png" height="50" class="mb-2"><h6 class="fw-bold">MACDEF Admin</h6></div><nav class="nav flex-column mt-3"><a class="nav-link p-3 active" href="dashboard.php"><i class="ri-dashboard-line me-2"></i> Dashboard</a><a class="nav-link p-3" href="contact_messages.php"><i class="ri-mail-line me-2"></i> Messages</a><a class="nav-link p-3" href="events.php"><i class="ri-calendar-line me-2"></i> Events</a><a class="nav-link p-3" href="gallery.php"><i class="ri-image-line me-2"></i> Gallery</a><a class="nav-link p-3" href="settings.php"><i class="ri-settings-3-line me-2"></i> Settings</a><hr class="mx-3 opacity-25"><a class="nav-link p-3 text-warning" href="logout.php"><i class="ri-logout-box-line me-2"></i> Logout</a></nav></div>
<div class="col-md-9 col-lg-10 ms-auto p-4 p-md-5"><h2 class="fw-bold">Dashboard Overview</h2><p>Welcome back, <?php echo e($_SESSION['full_name'] ?? 'Admin'); ?>.</p><?php if(!$pdo): ?><div class="alert alert-danger">Database not connected. Import <strong>database/macdef.sql</strong> and confirm includes/config.php credentials.</div><?php endif; ?><div class="row g-4 mt-2"><div class="col-md-4"><div class="card border-0 shadow-sm p-4 rounded-4"><div class="fs-1 fw-bold text-navy"><?php echo countRows('contact_submissions'); ?></div><div>Contact Messages</div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm p-4 rounded-4"><div class="fs-1 fw-bold text-navy"><?php echo countRows('events'); ?></div><div>Events</div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm p-4 rounded-4"><div class="fs-1 fw-bold text-navy"><?php echo countRows('gallery'); ?></div><div>Gallery Items</div></div></div></div></div>
</div></div></body></html>
